repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python2.7
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      language_version: python2.7
      exclude: docs/code_examples

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.7.0
    hooks:
    - id: setup-cfg-fmt
